USE [Aicellomilim_Iksan]
GO

/****** Object:  Table [dbo].[MESSIONTABLE]    Script Date: 2023-11-23 ¿ÀÈÄ 2:19:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MESSIONTABLE](
	[SEQ] [int] IDENTITY(1,1) NOT NULL,
	[JobId] [int] NOT NULL,
	[CALLNAME] [varchar](50) NOT NULL,
	[MESSIONSEQ] [varchar](10) NOT NULL,
	[LOCATION] [varchar](10) NULL,
	[CALLFLAG] [varchar](50) NULL,
	[CANCELFLAG] [varchar](50) NULL,
	[REGDATE] [datetime] NOT NULL,
 CONSTRAINT [PK__MESSIONT__CA1938C026E1B473] PRIMARY KEY CLUSTERED 
(
	[SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


